"""What an op handler may ask the canvas for (canvas v2 phase 1, 2.3): the ``OpContext`` protocol.

A kind module's ``OpSpec.create(ctx, op)`` validates its op and draws through
this interface only; ``canvas._KindCtx`` implements it over the batch being
applied. Kind modules never import ``canvas``, so a new kind is one module and
the canvas core never learns its name.

Every ``raise ctx.invalid(...)`` (or ``ctx.error``, ``ctx.too_big``) refuses
the op with the canvas's own error codes. Methods may be added; their meaning
never changes.

Pure: a ``typing.Protocol`` and nothing else.
"""
from __future__ import annotations

from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

try:  # ``typing.Protocol`` is 3.8+; the plugin supports 3.9, so this is only for type checkers on odd builds
    from typing import Protocol
except ImportError:  # pragma: no cover
    Protocol = object  # type: ignore[assignment,misc]

Element = Dict[str, Any]
Op = Mapping[str, Any]


class OpContext(Protocol):
    """The batch an op applies in, as a kind module sees it."""

    #: Who applies the batch (a member name, or ``human``), whether that is the operator, and the op's intent.
    author_name: str
    author_is_human: bool
    intent: str
    now: float
    team_name: str

    # -- refusals ---------------------------------------------------------------------------------------
    def invalid(self, field: str, message: str, **details: Any) -> Exception: ...
    def error(self, code: str, message: str, **details: Any) -> Exception: ...
    def too_big(self, field: str, limit: str, maximum: int, message: str) -> Exception: ...

    # -- reading fields -----------------------------------------------------------------------------------
    #: ``limit``: ``text`` (2,000), ``label`` (200, one line), ``comment`` (1,000), ``symbol`` (80). ``value`` reads
    #: something other than ``op[field]`` (a graph node's text), ``label`` names it in errors.
    def text(self, op: Op, field: str, *, limit: str = "text", one_line: bool = False, required: bool = False,
             value: Any = ..., label: Optional[str] = None) -> str: ...
    def choice(self, op: Op, field: str, choices: Sequence[str], default: str, *, value: Any = ..., label: Optional[str] = None) -> str: ...
    def number(self, op: Op, field: str, low: float, high: float, default: Optional[float] = None) -> Optional[float]: ...
    def boolean(self, op: Op, field: str, default: bool) -> bool: ...
    def points(self, op: Op, field: str, maximum: int, *, pressure: bool = False, minimum: int = 2, limit_name: str = "") -> List[List[float]]: ...
    def point(self, value: Any, field: str) -> List[float]: ...
    def is_point(self, value: Any) -> bool: ...
    def color(self, value: Any) -> str: ...
    def fill(self, value: Any) -> Optional[str]: ...
    def guard_code(self, text: str, field: str) -> None: ...

    # -- style and size -----------------------------------------------------------------------------------
    def style(self, op: Op, kind: str, base: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def default_style(self, kind: str) -> Dict[str, Any]: ...
    def size(self, op: Op, default_w: float, default_h: float) -> Tuple[float, float]: ...
    #: ``{"w", "h", "fit"}`` of an element sized from its label by its kind (``{}`` for a kind without ``measure``).
    def fit(self, el: Element, minimum: Tuple[float, float]) -> Dict[str, Any]: ...
    #: A free text's ``w``/``h``/``wrap``/``fit`` for its text, style and wrap width.
    def text_fields(self, el: Element, text: str, style: Dict[str, Any], wrap_w: Optional[float] = None) -> Dict[str, Any]: ...
    #: What a labelled element may not shrink below: an op's ``w``/``h``, else its ``fit.min``, else its size.
    def minimum(self, el: Element, w: Any = None, h: Any = None) -> Tuple[float, float]: ...
    def shape_size(self, kind: str) -> Tuple[float, float]: ...

    # -- the canvas ---------------------------------------------------------------------------------------
    def lookup(self, ref: Any, field: str) -> Element: ...
    def live(self) -> List[Element]: ...
    #: An element as this op would leave it (None when it was deleted).
    def el(self, eid: str) -> Optional[Element]: ...
    #: Whether the author may change ``el`` (its author, the manager for an agent's, the operator for anything).
    def may_edit(self, el: Element) -> bool: ...
    #: Record a change to an element (its ``updated_seq`` follows).
    def update(self, el: Element, **fields: Any) -> Element: ...
    #: A region (``"c1r2:c3r4"``, ``"x0,y0,x1,y1"``, a list, or an element's bounds) as ``[x0, y0, x1, y1]``.
    def region(self, value: Any, field: str) -> List[int]: ...
    #: ``(x, y, frame)`` for a new element of ``w`` x ``h`` from the op's placement (``at``, ``right_of`` ...).
    def place(self, op: Op, w: float, h: float, asked: Optional[Tuple[float, float]] = None) -> Tuple[float, float, Optional[str]]: ...
    def enclosing_frame(self, box: Sequence[float]) -> Optional[str]: ...
    def geometry(self, points: Sequence[Sequence[float]]) -> Dict[str, int]: ...
    #: A new element, recorded: alias and ``client_id`` come from ``op``; ``store`` maps fields to ``(bytes, kind)`` assets
    #: stored once the element is clear of locks. Then, by the kind: a sized kind makes way for its neighbours and sits
    #: on its host; a container or overlay is recorded as it is; anything else gets the claim and legibility warnings.
    def create(self, kind: str, x: float, y: float, w: float, h: float, *, op: Op, text: str = "", style: Optional[Dict[str, Any]] = None,
               frame: Optional[str] = None, store: Optional[Dict[str, Tuple[bytes, str]]] = None, **fields: Any) -> Element: ...
    #: An arrow's route from ``op``'s ``points`` or ``from``/``to``: ``(points, from id, to id)``; a labelled arrow
    #: between two elements makes room for its label.
    def route(self, op: Op, *, label: str, style: Dict[str, Any], curve: bool) -> Tuple[List[List[float]], Optional[str], Optional[str]]: ...
    #: An ``image`` op's picture: ``(bytes, mime, px_w, px_h)`` from ``path`` or ``asset``.
    def image(self, op: Op) -> Tuple[bytes, str, int, int]: ...
    #: A file under the team's artifacts, as the relative path an element stores.
    def artifact(self, rel: Any) -> str: ...
    def require_viz(self) -> None: ...
    #: A graph or Mermaid flowchart as a frame of native shapes and bound arrows (layout in Python).
    def expand_graph(self, op: Op, title: str, nodes: List[Dict[str, Any]], edges: List[Dict[str, Any]], algorithm: str,
                     direction: str, subgraphs: Sequence[Dict[str, Any]] = ()) -> None: ...
    def graph_nodes(self, raw: List[Any]) -> List[Dict[str, Any]]: ...
    def mentions(self, explicit: Any, text: str) -> List[str]: ...
    def warn(self, code: str, message: str, ids: Sequence[str]) -> None: ...
    #: The comment an op names (``reply_to``), or an ``element_unknown`` refusal.
    def comment(self, ref: Any, field: str) -> Element: ...
    #: A comment that mentions members: posted to them once the batch is applied.
    def mention(self, comment: Element) -> None: ...
