"""Watch readers: activity cards from what each harness already writes (``herdr_team.activity``, 0.21).

Every fixture is synthetic and lives under the ``TempState`` home, shaped like
the real stores: a Claude Code transcript (``tool_use`` blocks, ``TodoWrite``
and the newer task tools, usage records), a Codex rollout (``function_call``,
``custom_tool_call`` ``apply_patch``, ``update_plan``, ``token_count``), an
OpenCode ``opencode.db`` (``message``, ``part`` and ``todo`` tables) and a Pi
session file (``toolCall`` blocks). Format drift, redaction, and the
incremental, bounded reads are pinned here. Nothing reads the real HOME or
talks to a Herdr server.
"""
from __future__ import annotations

import json
import os
import sqlite3
import time
import unittest
from pathlib import Path
from typing import Any, Dict, List

from herdr_team import activity as A
from herdr_team import roster, store, transcripts
from herdr_team.errors import HerdrTeamError
from support import FAKE_MEMBERS, FakeApi, TempState, fake_agent

CLAUDE_ID = "11111111-aaaa-4bbb-8ccc-000000000001"
CODEX_ID = "01a0b063-aca2-7ac0-9559-d64f736d3e5c"
OPENCODE_ID = "ses_7f3a9c"
ANTHROPIC_KEY = "sk-ant-api03-" + "A" * 30
GITHUB_TOKEN = "ghp_" + "b" * 36
AWS_KEY = "AKIA" + "ABCDEFGHIJKLMNOP"


def iso(epoch: float) -> str:
    return transcripts.iso_of(epoch)


def session(kind: str, value: str, ref: str = "id") -> Dict[str, Any]:
    return {"source": "herdr:" + kind, "agent": kind, "kind": ref, "value": value}


def write_jsonl(path: Path, records: List[Any], tail: str = "") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [r if isinstance(r, str) else json.dumps(r) for r in records]
    path.write_text("\n".join(lines) + "\n" + tail, encoding="utf-8")
    return path


def append_jsonl(path: Path, records: List[Any], tail: str = "") -> None:
    with path.open("a", encoding="utf-8") as handle:
        for record in records:
            handle.write((record if isinstance(record, str) else json.dumps(record)) + "\n")
        handle.write(tail)


# -- Claude Code


def claude_user(text: Any, at: float, **extra: Any) -> Dict[str, Any]:
    record = {"type": "user", "timestamp": iso(at), "sessionId": CLAUDE_ID, "isSidechain": False,
              "message": {"role": "user", "content": text}}
    record.update(extra)
    return record


def claude_tool(name: str, args: Dict[str, Any], at: float, tool_id: str, model: str = "claude-opus-4-6", usage: Any = None) -> Dict[str, Any]:
    message: Dict[str, Any] = {"id": "msg_" + tool_id, "type": "message", "role": "assistant", "model": model,
                               "content": [{"type": "tool_use", "id": tool_id, "name": name, "input": args}]}
    if usage is not None:
        message["usage"] = usage
    return {"type": "assistant", "timestamp": iso(at), "sessionId": CLAUDE_ID, "isSidechain": False, "message": message}


def claude_result(tool_id: str, text: str, at: float) -> Dict[str, Any]:
    return {"type": "user", "timestamp": iso(at), "sessionId": CLAUDE_ID,
            "message": {"role": "user", "content": [{"type": "tool_result", "tool_use_id": tool_id, "content": text}]}}


def claude_transcript(now: float) -> List[Dict[str, Any]]:
    return [
        {"type": "file-history-snapshot", "messageId": "m0", "snapshot": {}},
        claude_user("Pull the Q3 exports and chart churn", now - 600),
        claude_user("<local-command-stdout>ok</local-command-stdout>", now - 590),
        claude_user("Caveat: the messages below were generated by the user while running local commands.", now - 589, isMeta=True),
        claude_tool("TodoWrite", {"todos": [
            {"content": "read the export spec", "status": "completed", "activeForm": "Reading the export spec"},
            {"content": "fetch Q3 exports", "status": "in_progress", "activeForm": "Fetching Q3 exports"},
            {"content": "chart churn", "status": "pending", "activeForm": "Charting churn"},
        ]}, now - 580, "toolu_todo1"),
        claude_tool("Read", {"file_path": "data/README.md"}, now - 570, "toolu_read1"),
        claude_result("toolu_read1", "SECRET-FILE-CONTENTS do not show", now - 569),
        claude_tool("Grep", {"pattern": "churn_rate", "path": "src/"}, now - 560, "toolu_grep1"),
        claude_tool("Edit", {"file_path": "src/pull.py", "old_string": "a", "new_string": "OLD-NEW-BODY"}, now - 550, "toolu_edit1"),
        claude_tool("Bash", {"command": "python pull.py --quarter 3\necho done", "description": "run the pull"}, now - 540, "toolu_bash1",
                    usage={"input_tokens": 10, "cache_creation_input_tokens": 1000, "cache_read_input_tokens": 400000, "output_tokens": 990}),
        claude_result("toolu_bash1", "pulled 12000 rows OUTPUT-NEVER-SHOWN", now - 530),
        claude_tool("WebFetch", {"url": "https://user:pw@docs.example.test/api?q=1", "prompt": "rate limits"}, now - 520, "toolu_web1"),
        claude_tool("mcp__synapse_canvas__look", {"region": "c1r1:c9r9"}, now - 515, "toolu_mcp1"),
        claude_tool("Task", {"subagent_type": "Explore", "description": "find the churn model", "prompt": "long prompt"}, now - 510, "toolu_task1"),
        {"type": "assistant", "timestamp": iso(now - 505), "isSidechain": True,
         "message": {"role": "assistant", "content": [{"type": "tool_use", "id": "toolu_side", "name": "Bash", "input": {"command": "sidechain-cmd"}}]}},
    ]


# -- Codex


def codex_item(payload: Dict[str, Any], at: float) -> Dict[str, Any]:
    return {"timestamp": iso(at), "type": "response_item", "payload": payload}


PATCH = "*** Begin Patch\n*** Update File: src/retry.py\n@@\n-old\n+new SECRET-PATCH-BODY\n*** Add File: tests/test_retry.py\n+x\n*** End Patch\n"


def codex_rollout(now: float) -> List[Dict[str, Any]]:
    return [
        {"timestamp": iso(now - 900), "type": "session_meta", "payload": {"id": CODEX_ID, "cwd": "/tmp/work"}},
        {"timestamp": iso(now - 899), "type": "turn_context", "payload": {"model": "gpt-5.6-luna", "cwd": "/tmp/work"}},
        codex_item({"type": "message", "role": "user", "content": [{"type": "input_text", "text": "<environment_context>cwd</environment_context>"}]}, now - 898),
        codex_item({"type": "message", "role": "developer", "content": [{"type": "input_text", "text": "instructions"}]}, now - 897),
        codex_item({"type": "message", "role": "user", "content": [{"type": "input_text", "text": "Harden the retry loop"}]}, now - 896),
        codex_item({"type": "function_call", "name": "update_plan", "call_id": "call_plan1", "arguments": json.dumps({
            "explanation": "three steps", "plan": [
                {"step": "read retry.py", "status": "completed"},
                {"step": "add jitter", "status": "in_progress"},
                {"step": "run the tests", "status": "pending"},
            ]})}, now - 890),
        codex_item({"type": "function_call", "name": "shell", "call_id": "call_sh1", "arguments": json.dumps({"command": ["bash", "-lc", "rg -n retry src/"], "workdir": "/tmp/work"})}, now - 880),
        codex_item({"type": "function_call_output", "call_id": "call_sh1", "output": json.dumps({"output": "src/retry.py:1: OUTPUT-NEVER-SHOWN"})}, now - 879),
        codex_item({"type": "custom_tool_call", "name": "apply_patch", "call_id": "call_patch1", "input": PATCH}, now - 870),
        codex_item({"type": "function_call", "name": "exec_command", "call_id": "call_ex1", "arguments": json.dumps({"cmd": "pytest -q tests/test_retry.py"})}, now - 860),
        codex_item({"type": "web_search_call", "id": "ws_1", "action": {"type": "search", "query": "exponential backoff jitter"}}, now - 855),
        {"timestamp": iso(now - 850), "type": "event_msg", "payload": {"type": "token_count", "info": {
            "total_token_usage": {"total_tokens": 494529}, "last_token_usage": {"total_tokens": 39195}, "model_context_window": 258400}}},
        {"timestamp": iso(now - 849), "type": "event_msg", "payload": {"type": "agent_message", "message": "echo"}},
    ]


# -- OpenCode


def opencode_db(home: Path, now: float, todo_table: bool = True) -> Path:
    path = home / ".local" / "share" / "opencode" / "opencode.db"
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(os.fspath(path))
    conn.execute("CREATE TABLE message (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, time_created INTEGER NOT NULL, time_updated INTEGER NOT NULL, data TEXT NOT NULL)")
    conn.execute("CREATE TABLE part (id TEXT PRIMARY KEY, message_id TEXT NOT NULL, session_id TEXT NOT NULL, time_created INTEGER NOT NULL, time_updated INTEGER NOT NULL, data TEXT NOT NULL)")
    if todo_table:
        conn.execute("CREATE TABLE todo (session_id TEXT NOT NULL, content TEXT NOT NULL, status TEXT NOT NULL, priority TEXT NOT NULL, position INTEGER NOT NULL, time_created INTEGER, time_updated INTEGER, PRIMARY KEY (session_id, position))")
    ms = int(now * 1000)
    messages = [
        ("msg_u1", {"role": "user"}, ms - 90_000),
        ("msg_a1", {"role": "assistant", "modelID": "claude-sonnet-4-5", "providerID": "anthropic", "tokens": {"total": 51234}}, ms - 80_000),
        ("msg_other", {"role": "assistant"}, ms - 1000),
    ]
    for message_id, data, at in messages:
        conn.execute("INSERT INTO message VALUES (?,?,?,?,?)", (message_id, OPENCODE_ID if message_id != "msg_other" else "ses_else", at, at, json.dumps(data)))
    parts = [
        ("prt_1", "msg_u1", {"type": "text", "text": "Speed up the search endpoint"}, ms - 89_000),
        ("prt_2", "msg_u1", {"type": "text", "text": "<system>injected context</system>", "synthetic": True}, ms - 88_900),
        ("prt_3", "msg_a1", {"type": "reasoning", "text": "thinking"}, ms - 88_000),
        ("prt_4", "msg_a1", {"type": "tool", "tool": "todowrite", "callID": "c0", "state": {"status": "completed", "input": {"todos": [
            {"content": "profile the endpoint", "status": "completed", "priority": "high", "id": "1"},
            {"content": "add an index", "status": "in_progress", "priority": "high", "id": "2"}]}, "output": "[]"}}, ms - 87_000),
        ("prt_5", "msg_a1", {"type": "tool", "tool": "bash", "callID": "c1", "state": {"status": "completed", "input": {"command": "go test ./search/...", "description": "run tests"}, "output": "OUTPUT-NEVER-SHOWN " + "x" * 5000}}, ms - 86_000),
        ("prt_6", "msg_a1", {"type": "tool", "tool": "edit", "callID": "c2", "state": {"status": "completed", "input": {"filePath": "/tmp/work/search/index.go", "oldString": "a", "newString": "EDIT-BODY"}, "output": ""}}, ms - 85_000),
        ("prt_7", "msg_a1", {"type": "text", "text": "ASSISTANT-REPLY-TEXT"}, ms - 84_000),
        ("prt_8", "msg_other", {"type": "tool", "tool": "bash", "state": {"input": {"command": "other-session-command"}}}, ms - 500),
    ]
    for part_id, message_id, data, at in parts:
        sess = "ses_else" if message_id == "msg_other" else OPENCODE_ID
        conn.execute("INSERT INTO part VALUES (?,?,?,?,?,?)", (part_id, message_id, sess, at, at, json.dumps(data)))
    if todo_table:
        for position, (content, status) in enumerate([("profile the endpoint", "completed"), ("add an index", "in_progress"), ("benchmark", "pending")]):
            conn.execute("INSERT INTO todo VALUES (?,?,?,?,?,?,?)", (OPENCODE_ID, content, status, "high", position, ms, ms))
    conn.commit()
    conn.close()
    return path


# -- Pi


def pi_session(path: Path, now: float) -> Path:
    return write_jsonl(path, [
        {"type": "session", "id": "pi1", "timestamp": iso(now - 700), "cwd": "/tmp/work"},
        {"type": "model_change", "id": "e1", "timestamp": iso(now - 699), "provider": "anthropic", "modelId": "claude-sonnet-4-5"},
        {"type": "message", "id": "m1", "timestamp": iso(now - 690), "message": {"role": "user", "content": [{"type": "text", "text": "Summarise the rate limit notes"}], "timestamp": int((now - 690) * 1000)}},
        {"type": "message", "id": "m2", "timestamp": iso(now - 680), "message": {"role": "assistant", "content": [
            {"type": "thinking", "thinking": "hmm"},
            {"type": "toolCall", "id": "tc1", "name": "read", "arguments": {"path": "notes/rate-limit.md"}},
            {"type": "toolCall", "id": "tc2", "name": "bash", "arguments": {"command": "wc -l notes/*.md"}}]}},
        {"type": "message", "id": "m3", "timestamp": iso(now - 670), "message": {"role": "toolResult", "toolCallId": "tc1", "toolName": "read", "content": [{"type": "text", "text": "OUTPUT-NEVER-SHOWN"}]}},
        {"type": "message", "id": "m4", "timestamp": iso(now - 660), "message": {"role": "assistant", "content": [
            {"type": "toolCall", "id": "tc3", "name": "write", "arguments": {"path": "notes/summary.md", "content": "WRITE-BODY"}}]}},
    ])


class Base(unittest.TestCase):
    def setUp(self) -> None:
        self.now = time.time()
        self.ts = TempState()
        self.addCleanup(self.ts.cleanup)
        self.env = dict(self.ts.env)
        self.home = self.ts.home
        self.layout = self.ts.layout

    def claude_path(self, value: str = CLAUDE_ID) -> Path:
        return self.home / ".claude" / "projects" / "-tmp-work" / "{}.jsonl".format(value)

    def codex_path(self) -> Path:
        return self.home / ".codex" / "sessions" / "2026" / "09" / "26" / "rollout-2026-09-26T10-00-00-{}.jsonl".format(CODEX_ID)

    def target(self, kind: str, value: str, ref: str = "id", terminal: str = "term_x", name: str = "watched-one") -> Dict[str, Any]:
        return {"terminal_id": terminal, "pane_id": "w3:p2", "name": name, "kind": kind, "team": None, "session": session(kind, value, ref)}

    def live(self, kind: str, terminal: str = "term_x", title: str = "Pulling Q3 exports", status: str = "working", **extra: Any) -> Dict[str, Any]:
        return fake_agent("w3:p2", terminal, kind, "watched-one", status=status, terminal_title_stripped=title, **extra)

    def card(self, target: Dict[str, Any], live: Any = "default", **kwargs: Any) -> Dict[str, Any]:
        if live == "default":
            live = self.live(str(target.get("kind")), str(target.get("terminal_id")))
        return A.card(self.layout, target, live=live, env=self.env, **kwargs)


# --------------------------------------------------------------------------


class DescribeToolTests(unittest.TestCase):
    def test_each_tool_is_its_name_or_one_short_argument(self):
        cases = [
            (("Bash", {"command": "python pull.py\necho done"}), ("run", "python pull.py", [])),
            (("shell", {"command": ["bash", "-lc", "rg -n retry src/"]}), ("run", "rg -n retry src/", [])),
            (("shell", {"command": ["git", "status", "--short"]}), ("run", "git status --short", [])),
            (("exec_command", {"cmd": "pytest -q"}), ("run", "pytest -q", [])),
            (("Edit", {"file_path": "src/a.py", "old_string": "x", "new_string": "BODY"}), ("edit", "src/a.py", ["src/a.py"])),
            (("write", {"filePath": "/w/b.go", "content": "BODY"}), ("edit", "/w/b.go", ["/w/b.go"])),
            (("apply_patch", {"input": PATCH}), ("edit", "src/retry.py +1", ["src/retry.py", "tests/test_retry.py"])),
            (("Read", {"file_path": "data/README.md"}), ("read", "data/README.md", [])),
            (("Grep", {"pattern": "churn", "path": "src/"}), ("search", '"churn" in src/', [])),
            (("Glob", {"pattern": "**/*.py"}), ("search", '"**/*.py"', [])),
            (("WebFetch", {"url": "https://user:secret@docs.example.test/x?y=1", "prompt": "p"}), ("web", "docs.example.test", [])),
            (("WebSearch", {"query": "backoff jitter"}), ("web", "backoff jitter", [])),
            (("Task", {"subagent_type": "Explore", "description": "find it", "prompt": "LONG"}), ("agent", "Explore find it", [])),
            (("mcp__synapse_canvas__look", {"region": "x"}), ("mcp", "synapse_canvas look", [])),
            (("SomethingNew", {"secret_arg": "value"}), ("tool", "SomethingNew", [])),
        ]
        for (name, args), expected in cases:
            self.assertEqual(A.describe_tool(name, args), expected, name)

    def test_a_patch_typed_through_the_shell_is_an_edit(self):
        heredoc = "apply_patch <<'EOF'\n" + PATCH + "EOF"
        self.assertEqual(A.describe_tool("shell", {"command": ["bash", "-lc", heredoc]}), ("edit", "src/retry.py +1", ["src/retry.py", "tests/test_retry.py"]))
        self.assertEqual(A.describe_tool("shell", {"command": ["apply_patch", PATCH]})[0], "edit")

    def test_odd_arguments_never_raise(self):
        for args in (None, "a string", 3, [], {"command": 7}, {"file_path": ["x"]}, {"url": 5}):
            icon, text, files = A.describe_tool("Bash", args) or ("", "", [])
            self.assertTrue(text)
            A.describe_tool("Edit", args)
            A.describe_tool("WebFetch", args)
        self.assertIsNone(A.describe_tool("", {}))
        self.assertIsNone(A.describe_tool(None, {}))

    def test_arguments_are_redacted_and_clipped(self):
        icon, text, _ = A.describe_tool("Bash", {"command": "curl -H 'Authorization: Bearer {}' https://x".format("t" * 40)})
        self.assertIn("[redacted:bearer_token]", text)
        icon, text, _ = A.describe_tool("Bash", {"command": "export GITHUB_TOKEN={}".format(GITHUB_TOKEN)})
        self.assertNotIn(GITHUB_TOKEN, text)
        self.assertIn("[redacted:", text)
        icon, text, _ = A.describe_tool("Bash", {"command": "echo " + "y" * 500})
        self.assertLessEqual(len(text), A.ACTION_CHARS)
        self.assertTrue(text.endswith("…"))
        icon, text, _ = A.describe_tool("Bash", {"command": "printf '\x1b[31mred\x1b[0m'\ttab"})
        self.assertNotIn("\x1b", text)

    def test_redact_covers_the_board_and_the_stricter_shapes(self):
        text = A.redact("keys {} {} {} and -----BEGIN RSA PRIVATE KEY-----\nabc\n-----END RSA PRIVATE KEY----- done".format(ANTHROPIC_KEY, AWS_KEY, "sk-" + "q" * 17))
        for secret in (ANTHROPIC_KEY, AWS_KEY, "sk-" + "q" * 17, "abc"):
            self.assertNotIn(secret, text)
        self.assertIn("[redacted:anthropic_key]", text)
        self.assertIn("[redacted:private_key]", text)


class PlanTests(unittest.TestCase):
    def test_steps_and_the_current_one(self):
        steps = A.todo_steps([{"content": "a", "status": "completed"}, {"step": "b", "status": "in_progress"}, {"subject": "c", "status": "weird"},
                              "not a dict", {"status": "pending"}])
        self.assertEqual(steps, [{"text": "a", "status": "completed"}, {"text": "b", "status": "in_progress"}, {"text": "c", "status": "pending"}])
        plan = A.make_plan(steps, "todo")
        self.assertEqual((plan["current"], plan["total"], plan["source"]), (2, 3, "todo"))
        self.assertIsNone(A.make_plan([], "todo"))
        self.assertIsNone(A.make_plan([{"text": "a", "status": "completed"}], "todo")["current"])
        self.assertEqual(A.todo_steps([{"content": "x", "status": "Done"}, {"content": "y", "status": "in progress"}])[0]["status"], "completed")
        self.assertEqual(A.todo_steps([{"content": "y", "status": "in progress"}])[0]["status"], "in_progress")

    def test_a_long_plan_is_capped_but_counted(self):
        plan = A.make_plan([{"text": str(i), "status": "pending"} for i in range(80)], "update_plan")
        self.assertEqual((len(plan["steps"]), plan["total"]), (A.MAX_PLAN_STEPS, 80))


class ClaudeReaderTests(Base):
    def setUp(self) -> None:
        super().setUp()
        self.path = write_jsonl(self.claude_path(), claude_transcript(self.now))

    def test_the_card_carries_title_state_plan_actions_files_context_and_prompt(self):
        card = self.card(self.target("claude", CLAUDE_ID))
        self.assertEqual((card["state"], card["headline"], card["kind"], card["reader"], card["reader_error"]),
                         ("working", "Pulling Q3 exports", "claude", "claude", None))
        self.assertEqual(card["plan"]["source"], "todo")
        self.assertEqual((card["plan"]["current"], card["plan"]["total"]), (2, 3))
        self.assertEqual(card["plan"]["steps"][1], {"text": "fetch Q3 exports", "status": "in_progress"})
        self.assertEqual([(a["icon"], a["text"]) for a in card["actions"]], [
            ("agent", "Explore find the churn model"),
            ("mcp", "synapse_canvas look"),
            ("web", "docs.example.test"),
            ("run", "python pull.py --quarter 3"),
            ("edit", "src/pull.py"),
            ("search", '"churn_rate" in src/'),
            ("read", "data/README.md"),
        ])
        self.assertTrue(all(a["at"] and a["at"].endswith("Z") for a in card["actions"]))
        self.assertEqual(card["files"], ["src/pull.py"])
        self.assertEqual(card["context"]["used"], 402000)
        self.assertAlmostEqual(card["context"]["percent"], 40.2)
        self.assertEqual(card["last_prompt"], "Pull the Q3 exports and chart churn")
        self.assertEqual(card["doing"], "▶ 2/3 fetch Q3 exports")
        self.assertEqual(set(card), {"key", "terminal_id", "pane_id", "name", "team", "role", "kind", "profile", "watched", "state",
                                     "headline", "plan", "actions", "files", "context", "last_prompt", "doing", "reader",
                                     "reader_error", "reader_note", "updated_at"})

    def test_output_contents_and_sidechains_never_reach_the_card(self):
        card = self.card(self.target("claude", CLAUDE_ID))
        dumped = json.dumps(card)
        for hidden in ("OUTPUT-NEVER-SHOWN", "SECRET-FILE-CONTENTS", "OLD-NEW-BODY", "sidechain-cmd", "user:pw", "long prompt", "echo done"):
            self.assertNotIn(hidden, dumped)

    def test_redaction_reaches_prompts_commands_and_paths(self):
        append_jsonl(self.path, [
            claude_user("use the key {} please".format(ANTHROPIC_KEY), self.now - 100),
            claude_tool("Bash", {"command": "AWS_ACCESS_KEY_ID={} aws s3 ls".format(AWS_KEY)}, self.now - 90, "toolu_s1"),
            claude_tool("Write", {"file_path": "/tmp/{}/notes.md".format(GITHUB_TOKEN), "content": "x"}, self.now - 80, "toolu_s2"),
        ])
        card = self.card(self.target("claude", CLAUDE_ID))
        dumped = json.dumps(card)
        for secret in (ANTHROPIC_KEY, AWS_KEY, GITHUB_TOKEN):
            self.assertNotIn(secret, dumped)
        self.assertIn("[redacted:anthropic_key]", card["last_prompt"])
        self.assertIn("[redacted:aws_access_key]", card["actions"][1]["text"])
        cache = store.read_json(A.cache_path(self.ts.session, "term_x"))
        self.assertNotIn(ANTHROPIC_KEY, json.dumps(cache), "the cache holds only redacted text")

    def test_reads_are_incremental_and_a_half_written_line_waits(self):
        target = self.target("claude", CLAUDE_ID)
        self.card(target)
        cache = store.read_json(A.cache_path(self.ts.session, "term_x"))
        self.assertEqual(cache["offset"], self.path.stat().st_size)
        record = json.dumps(claude_tool("Bash", {"command": "make chart"}, self.now - 50, "toolu_new"))
        append_jsonl(self.path, [], tail=record[:40])  # the harness is mid-write
        card = self.card(target)
        self.assertEqual(card["actions"][0]["text"], "Explore find the churn model", "a partial line is not consumed")
        self.assertEqual(store.read_json(A.cache_path(self.ts.session, "term_x"))["offset"], cache["offset"])
        append_jsonl(self.path, [], tail=record[40:] + "\n")
        card = self.card(target)
        self.assertEqual(card["actions"][0], {"icon": "run", "text": "make chart", "at": iso(self.now - 50)})
        self.assertEqual(card["doing"], "▶ 2/3 fetch Q3 exports", "the plan still wins")
        self.assertEqual(len([a for a in card["actions"] if a["text"] == "make chart"]), 1)
        self.assertEqual(len(card["actions"]), 8)

    def test_a_reread_from_an_older_offset_does_not_duplicate(self):
        target = self.target("claude", CLAUDE_ID)
        first = self.card(target)
        path = A.cache_path(self.ts.session, "term_x")
        cache = store.read_json(path)
        cache["offset"] = 0  # a concurrent reader wrote an older cache
        store.write_json(path, cache)
        again = self.card(target)
        self.assertEqual(again["actions"], first["actions"])
        self.assertEqual(again["files"], first["files"])

    def test_image_sized_lines_between_actions_do_not_hide_them(self):
        """Live, 2026-09-26: a 64 KB window behind an 83 KB image result showed 2 of 6 actions."""
        image = {"type": "user", "timestamp": "2026-09-26T20:29:26Z",
                 "message": {"role": "user", "content": [{"type": "tool_result", "tool_use_id": "toolu_look",
                                                          "content": [{"type": "image", "source": {"type": "base64", "data": "A" * 90000}}]}]}}
        attachment = {"type": "attachment", "timestamp": "2026-09-26T20:29:20Z", "attachment": {"content": "B" * 180000}}
        rows = [claude_tool("Bash", {"command": "herdr-synapse board --new"}, self.now - 60, "toolu_1"),
                claude_tool("mcp__synapse_canvas__canvas_claim", {"label": "house"}, self.now - 50, "toolu_2"),
                attachment,
                claude_tool("mcp__synapse_canvas__canvas_draw", {"ops": []}, self.now - 40, "toolu_3"),
                claude_tool("mcp__synapse_canvas__canvas_look", {}, self.now - 30, "toolu_look"),
                image,
                claude_tool("Bash", {"command": "herdr-synapse post done"}, self.now - 10, "toolu_4")]
        write_jsonl(self.path, rows)
        state: Dict[str, Any] = {}
        A.read_jsonl(state, self.path, A.claude_record, A._Activity(state, "todo"))
        texts = " ".join(a["text"] for a in state["actions"])
        for want in ("canvas_claim", "canvas_draw", "canvas_look", "board --new", "post done"):
            self.assertIn(want, texts)

    def test_the_first_read_is_bounded_to_the_newest_bytes(self):
        filler = [claude_tool("Read", {"file_path": "old/file{}.py".format(i)}, self.now - 50000 + i, "toolu_f{}".format(i)) for i in range(9000)]
        write_jsonl(self.path, filler + [claude_tool("Edit", {"file_path": "src/newest.py"}, self.now - 10, "toolu_last")])
        self.assertGreater(self.path.stat().st_size, 2 * A.FIRST_READ_BYTES)
        state: Dict[str, Any] = {}
        read = A.read_jsonl(state, self.path, A.claude_record, A._Activity(state, "todo"))
        self.assertLessEqual(read, A.FIRST_READ_BYTES)
        self.assertEqual(state["offset"], self.path.stat().st_size)
        self.assertEqual(state["actions"][0]["text"], "src/newest.py")
        self.assertNotIn("old/file0.py", json.dumps(state))
        self.assertIsNone(state["error"])

    def test_a_backlog_longer_than_the_budget_jumps_to_the_newest(self):
        target = self.target("claude", CLAUDE_ID)
        self.card(target)
        append_jsonl(self.path, [claude_tool("Read", {"file_path": "skipped/{}.py".format(i)}, self.now, "toolu_b{}".format(i)) for i in range(700)]
                     + [claude_tool("Bash", {"command": "the newest command"}, self.now, "toolu_b_last")])
        card = self.card(target)
        self.assertEqual(card["actions"][0]["text"], "the newest command")
        self.assertEqual(store.read_json(A.cache_path(self.ts.session, "term_x"))["offset"], self.path.stat().st_size)

    def test_a_line_longer_than_the_budget_is_skipped(self):
        huge = claude_tool("Write", {"file_path": "big.txt", "content": "z" * (A.MAX_READ_BYTES + 1000)}, self.now, "toolu_huge")
        write_jsonl(self.path, [claude_user("hi", self.now - 5)])
        target = self.target("claude", CLAUDE_ID)
        self.card(target)
        append_jsonl(self.path, [huge, claude_tool("Bash", {"command": "after the big one"}, self.now, "toolu_after")])
        for _ in range(3):
            card = self.card(target)
        self.assertEqual(card["actions"][0]["text"], "after the big one")
        self.assertIsNone(card["reader_error"])

    def test_a_giant_line_still_being_written_is_skipped_to_its_end(self):
        write_jsonl(self.path, [claude_user("hi", self.now - 5)])
        state: Dict[str, Any] = {}
        A.read_jsonl(state, self.path, A.claude_record, A._Activity(state, "todo"))
        append_jsonl(self.path, [], tail='{"type": "assistant", "message": {"content": "' + "z" * (A.MAX_READ_BYTES * 2))
        read = A.read_jsonl(state, self.path, A.claude_record, A._Activity(state, "todo"))
        self.assertLessEqual(read, A.MAX_READ_BYTES)
        self.assertEqual((state["offset"], state["mid_line"]), (self.path.stat().st_size, True))
        append_jsonl(self.path, [], tail='"}}\n' + json.dumps(claude_tool("Bash", {"command": "after it"}, self.now, "toolu_z")) + "\n")
        A.read_jsonl(state, self.path, A.claude_record, A._Activity(state, "todo"))
        self.assertEqual(state["actions"][0]["text"], "after it")
        self.assertEqual((state["offset"], state["mid_line"], state["error"]), (self.path.stat().st_size, False, None))

    def test_the_task_tools_make_a_plan_counted_once(self):
        write_jsonl(self.path, [
            claude_tool("TaskCreate", {"subject": "write the loader", "description": "d", "activeForm": "Writing"}, self.now - 30, "toolu_t1"),
            claude_tool("TaskCreate", {"subject": "test the loader", "description": "d"}, self.now - 29, "toolu_t2"),
            claude_tool("TaskCreate", {"subject": "drop me", "description": "d"}, self.now - 28, "toolu_t3"),
            claude_tool("TaskUpdate", {"taskId": "1", "status": "completed"}, self.now - 27, "toolu_t4"),
            claude_tool("TaskUpdate", {"taskId": "2", "status": "in_progress"}, self.now - 26, "toolu_t5"),
            claude_tool("TaskUpdate", {"taskId": "3", "status": "deleted"}, self.now - 25, "toolu_t6"),
            claude_tool("TaskUpdate", {"taskId": "99", "status": "completed"}, self.now - 24, "toolu_t7"),
            claude_tool("TaskList", {}, self.now - 23, "toolu_t8"),
        ])
        target = self.target("claude", CLAUDE_ID)
        card = self.card(target)
        self.assertEqual(card["plan"], {"steps": [{"text": "write the loader", "status": "completed"}, {"text": "test the loader", "status": "in_progress"}],
                                        "current": 2, "total": 2, "source": "todo"})
        self.assertEqual(card["actions"], [], "plan tools are the plan, not actions")
        path = A.cache_path(self.ts.session, "term_x")
        cache = store.read_json(path)
        cache["offset"] = 0
        store.write_json(path, cache)
        self.assertEqual(self.card(target)["plan"]["total"], 2, "a re-read counts each TaskCreate once")

    def test_slash_commands_and_shell_input_read_as_prompts(self):
        write_jsonl(self.path, [claude_user("<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>opus</command-args>", self.now - 20)])
        self.assertEqual(self.card(self.target("claude", CLAUDE_ID))["last_prompt"], "/model opus")
        append_jsonl(self.path, [claude_user("<bash-input>git status</bash-input>", self.now - 10)])
        self.assertEqual(self.card(self.target("claude", CLAUDE_ID))["last_prompt"], "! git status")
        append_jsonl(self.path, [claude_user([{"type": "text", "text": "a list-shaped prompt"}], self.now - 5)])
        self.assertEqual(self.card(self.target("claude", CLAUDE_ID))["last_prompt"], "a list-shaped prompt")

    def test_the_hook_recorded_path_wins_over_the_lookup(self):
        elsewhere = self.ts.tmp / "custom" / "{}.jsonl".format(CLAUDE_ID)
        write_jsonl(elsewhere, [claude_tool("Bash", {"command": "from the hook path"}, self.now, "toolu_h")])
        store.write_json(self.ts.session.pane_record("term_x"), {"team": "alpha", "name": "watched-one", "gen": 1, "transcript_path": os.fspath(elsewhere)})
        self.assertEqual(self.card(self.target("claude", CLAUDE_ID))["actions"][0]["text"], "from the hook path")

    def test_a_new_conversation_starts_over(self):
        target = self.target("claude", CLAUDE_ID)
        self.assertTrue(self.card(target)["actions"])
        other = "22222222-aaaa-4bbb-8ccc-000000000002"
        write_jsonl(self.claude_path(other), [claude_user("fresh start", self.now)])
        card = self.card(dict(target, session=session("claude", other)))
        self.assertEqual((card["actions"], card["plan"], card["last_prompt"]), ([], None, "fresh start"))

    def test_the_live_rows_session_is_preferred_and_the_roster_is_the_fallback(self):
        other = "33333333-aaaa-4bbb-8ccc-000000000003"
        write_jsonl(self.claude_path(other), [claude_user("the live conversation", self.now)])
        live = self.live("claude", agent_session={"source": "herdr:claude", "agent": "claude", "kind": "id", "value": other})
        self.assertEqual(self.card(self.target("claude", CLAUDE_ID), live=live)["last_prompt"], "the live conversation")


class CodexReaderTests(Base):
    def setUp(self) -> None:
        super().setUp()
        write_jsonl(self.codex_path(), codex_rollout(self.now))

    def test_plan_patch_commands_search_and_context(self):
        card = self.card(self.target("codex", CODEX_ID))
        self.assertEqual((card["reader"], card["reader_error"]), ("codex", None))
        self.assertEqual(card["plan"]["source"], "update_plan")
        self.assertEqual((card["plan"]["current"], card["plan"]["total"]), (2, 3))
        self.assertEqual([(a["icon"], a["text"]) for a in card["actions"]], [
            ("web", "exponential backoff jitter"),
            ("run", "pytest -q tests/test_retry.py"),
            ("edit", "src/retry.py +1"),
            ("run", "rg -n retry src/"),
        ])
        self.assertEqual(card["files"], ["tests/test_retry.py", "src/retry.py"])
        self.assertEqual(card["context"], {"percent": round(39195 * 100.0 / 258400, 1), "used": 39195, "window": 258400})
        self.assertEqual(card["last_prompt"], "Harden the retry loop")
        self.assertEqual(card["doing"], "▶ 2/3 add jitter")
        dumped = json.dumps(card)
        for hidden in ("OUTPUT-NEVER-SHOWN", "SECRET-PATCH-BODY", "environment_context", "instructions"):
            self.assertNotIn(hidden, dumped)

    def test_without_a_plan_the_last_edit_then_the_last_command_then_the_title(self):
        write_jsonl(self.codex_path(), [r for r in codex_rollout(self.now) if (r.get("payload") or {}).get("name") != "update_plan"])
        card = self.card(self.target("codex", CODEX_ID))
        self.assertIsNone(card["plan"])
        self.assertEqual(card["doing"], "✎ retry.py +1")


class OpenCodeReaderTests(Base):
    def setUp(self) -> None:
        super().setUp()
        self.db = opencode_db(self.home, self.now)

    def test_parts_todos_prompt_and_tokens(self):
        card = self.card(self.target("opencode", OPENCODE_ID))
        self.assertEqual((card["reader"], card["reader_error"]), ("opencode", None))
        self.assertEqual(card["plan"], {"steps": [{"text": "profile the endpoint", "status": "completed"}, {"text": "add an index", "status": "in_progress"},
                                                  {"text": "benchmark", "status": "pending"}], "current": 2, "total": 3, "source": "opencode_todo"})
        self.assertEqual([(a["icon"], a["text"]) for a in card["actions"]], [("edit", "/tmp/work/search/index.go"), ("run", "go test ./search/...")])
        self.assertEqual(card["files"], ["/tmp/work/search/index.go"])
        self.assertEqual(card["last_prompt"], "Speed up the search endpoint")
        self.assertEqual(card["context"]["used"], 51234)
        dumped = json.dumps(card)
        for hidden in ("OUTPUT-NEVER-SHOWN", "EDIT-BODY", "ASSISTANT-REPLY-TEXT", "injected context", "other-session-command"):
            self.assertNotIn(hidden, dumped)

    def test_new_and_updated_parts_arrive_incrementally(self):
        target = self.target("opencode", OPENCODE_ID)
        self.card(target)
        cursor = store.read_json(A.cache_path(self.ts.session, "term_x"))["cursor"]
        conn = sqlite3.connect(os.fspath(self.db))
        later = int(self.now * 1000) + 5
        # a tool part first written without its input, then updated in place
        conn.execute("INSERT INTO part VALUES (?,?,?,?,?,?)", ("prt_9", "msg_a1", OPENCODE_ID, later, later, json.dumps({"type": "tool", "tool": "read", "state": {"status": "pending", "input": {}}})))
        conn.commit()
        card = self.card(target)
        self.assertEqual(card["actions"][0], {"icon": "read", "text": "read", "at": iso(later / 1000.0)})
        conn.execute("UPDATE part SET time_updated = ?, data = ? WHERE id = 'prt_9'", (later + 10, json.dumps({"type": "tool", "tool": "read", "state": {"status": "running", "input": {"filePath": "search/query.go"}}})))
        conn.commit()
        conn.close()
        card = self.card(target)
        self.assertEqual([a["text"] for a in card["actions"]][:2], ["search/query.go", "/tmp/work/search/index.go"])
        self.assertEqual(len(card["actions"]), 3, "the updated part replaced its first version")
        self.assertGreater(store.read_json(A.cache_path(self.ts.session, "term_x"))["cursor"], cursor)

    def test_a_quiet_refresh_reads_no_context_and_no_todos(self):
        target = self.target("opencode", OPENCODE_ID)
        self.card(target)
        from unittest import mock

        with mock.patch.object(A._context, "read_opencode") as reading, mock.patch.object(A, "_opencode_todo") as todos:
            self.card(target)
            self.card(target)
        reading.assert_not_called()
        todos.assert_not_called()

    def test_without_a_todo_table_the_todowrite_part_is_the_plan(self):
        os.unlink(self.db)
        opencode_db(self.home, self.now, todo_table=False)
        card = self.card(self.target("opencode", OPENCODE_ID))
        self.assertEqual(card["plan"]["source"], "opencode_todo")
        self.assertEqual((card["plan"]["current"], card["plan"]["total"]), (2, 2))


class PiReaderTests(Base):
    def test_tool_calls_prompt_and_no_plan(self):
        path = pi_session(self.ts.tmp / "pi" / "2026-09-26T10-00-00-000Z_pi1.jsonl", self.now)
        card = self.card(self.target("pi", os.fspath(path), ref="path"))
        self.assertEqual((card["reader"], card["reader_error"], card["plan"]), ("pi", None, None))
        self.assertEqual([(a["icon"], a["text"]) for a in card["actions"]], [("edit", "notes/summary.md"), ("run", "wc -l notes/*.md"), ("read", "notes/rate-limit.md")])
        self.assertEqual(card["files"], ["notes/summary.md"])
        self.assertEqual(card["last_prompt"], "Summarise the rate limit notes")
        self.assertEqual(card["doing"], "✎ summary.md")
        self.assertNotIn("WRITE-BODY", json.dumps(card))
        self.assertNotIn("OUTPUT-NEVER-SHOWN", json.dumps(card))

    def test_context_comes_from_the_extension_snapshot(self):
        from herdr_team import pi_support

        path = pi_session(self.ts.tmp / "pi" / "2026-09-26T10-00-00-000Z_pi1.jsonl", self.now)
        ref = session("pi", os.fspath(path), "path")
        snapshot = pi_support.snapshot_path(self.ts.session, "term_x")
        snapshot.parent.mkdir(parents=True, exist_ok=True)
        store.write_json(snapshot, {"version": 1, "at": time.time(), "session": os.fspath(path), "instance": "i1", "provider": "anthropic",
                                    "model": "claude-sonnet-4-5", "effort": None, "used": 50000, "window": 200000, "compact": None,
                                    "pane_id": "w3:p2", "terminal_id": "term_x"})
        card = self.card(dict(self.target("pi", os.fspath(path), ref="path"), session=ref))
        self.assertEqual(card["context"], {"percent": 25.0, "used": 50000, "window": 200000})

    def test_a_pi_session_by_id_is_found_under_the_agent_dir(self):
        env = dict(self.env, PI_CODING_AGENT_DIR=os.fspath(self.ts.tmp / "pi-agent"))
        pi_session(self.ts.tmp / "pi-agent" / "sessions" / "--tmp-work--" / "2026-09-26T10-00-00-000Z_abc123.jsonl", self.now)
        card = A.card(self.layout, self.target("pi", "abc123"), live=self.live("pi"), env=env)
        self.assertEqual(card["last_prompt"], "Summarise the rate limit notes")


class DriftTests(Base):
    def test_an_unknown_claude_envelope_is_unknown_but_the_title_and_state_stay(self):
        write_jsonl(self.claude_path(), [{"kind": "turn", "body": {"tool": "Bash"}} for _ in range(3)])
        card = self.card(self.target("claude", CLAUDE_ID))
        self.assertEqual((card["reader_error"], card["headline"], card["state"]), ("unknown", "Pulling Q3 exports", "working"))
        self.assertEqual(card["actions"], [])
        self.assertEqual(card["doing"], "Pulling Q3 exports")

    def test_a_message_that_changed_shape_is_drift(self):
        write_jsonl(self.claude_path(), [{"type": "assistant", "msg": {"content": []}}, {"type": "user", "message": "flat text"}])
        self.assertEqual(self.card(self.target("claude", CLAUDE_ID))["reader_error"], "unknown")

    def test_odd_fields_inside_a_known_envelope_are_skipped_quietly(self):
        write_jsonl(self.claude_path(), [
            {"type": "assistant", "message": {"role": "assistant", "content": [{"type": "tool_use", "name": "Bash", "input": "not a dict"}, "junk", {"type": "tool_use"}]}},
            {"type": "assistant", "message": {"role": "assistant", "content": "plain string content", "usage": {"input_tokens": "many"}}},
            {"type": "user", "message": {"role": "user", "content": None}},
            {"type": "future-record-kind", "anything": 1},
        ])
        card = self.card(self.target("claude", CLAUDE_ID))
        self.assertIsNone(card["reader_error"])
        self.assertEqual([(a["icon"], a["text"]) for a in card["actions"]], [("run", "Bash")])

    def test_garbage_lines_among_records_are_tolerated_but_not_a_majority(self):
        write_jsonl(self.codex_path(), codex_rollout(self.now)[:6] + ["plain text line", "{not json"])
        self.assertIsNone(self.card(self.target("codex", CODEX_ID))["reader_error"])
        append_jsonl(self.codex_path(), ["<html>", "garbage", "{\"payload\": 1}"])
        card = self.card(self.target("codex", CODEX_ID))
        self.assertEqual(card["reader_error"], "unknown")
        self.assertEqual(card["plan"]["source"], "update_plan", "what was read before stays")

    def test_an_opencode_schema_change_is_unknown(self):
        path = self.home / ".local" / "share" / "opencode" / "opencode.db"
        path.parent.mkdir(parents=True)
        conn = sqlite3.connect(os.fspath(path))
        conn.execute("CREATE TABLE part (id TEXT, payload TEXT)")
        conn.commit()
        conn.close()
        card = self.card(self.target("opencode", OPENCODE_ID))
        self.assertEqual((card["reader_error"], card["headline"]), ("unknown", "Pulling Q3 exports"))

    def test_a_missing_store_or_session_is_unknown_with_a_reason(self):
        card = self.card(self.target("claude", "44444444-aaaa-4bbb-8ccc-000000000004"))
        self.assertEqual(card["reader_error"], "unknown")
        self.assertIn("not found", card["reader_note"])
        card = self.card(self.target("opencode", OPENCODE_ID))
        self.assertEqual(card["reader_error"], "unknown")
        target = self.target("codex", CODEX_ID)
        target["session"] = None
        card = self.card(target)
        self.assertEqual(card["reader_error"], "unknown")
        self.assertIn("herdr integration install codex", card["reader_note"])

    def test_a_missing_file_is_looked_for_again_only_after_a_minute(self):
        from unittest import mock

        target = self.target("claude", CLAUDE_ID)
        with mock.patch.object(A._context, "claude_transcript_by_id", wraps=A._context.claude_transcript_by_id) as lookup:
            self.assertEqual(self.card(target)["reader_error"], "unknown")
            write_jsonl(self.claude_path(), claude_transcript(self.now))
            self.assertEqual(self.card(target)["reader_error"], "unknown")
            self.assertEqual(lookup.call_count, 1)
            path = A.cache_path(self.ts.session, "term_x")
            cache = store.read_json(path)
            cache["missing_at"] -= A.LOOKUP_RETRY_S + 1
            store.write_json(path, cache)
            card = self.card(target)
            self.assertEqual(lookup.call_count, 2)
        self.assertEqual((card["reader_error"], card["reader_note"], card["plan"]["current"]), (None, None, 2))

    def test_an_unsafe_session_id_is_never_globbed(self):
        card = self.card(self.target("claude", "../../etc/*"))
        self.assertEqual(card["reader_error"], "unknown")


class CardTests(Base):
    def test_a_kind_without_a_reader_shows_title_and_state_only(self):
        card = self.card({"terminal_id": "term_g", "pane_id": "w3:p2", "name": "gem", "kind": "gemini"}, live=self.live("gemini", "term_g", title="Refactoring the parser", status="idle"))
        self.assertEqual((card["reader"], card["reader_error"], card["state"], card["actions"], card["plan"]), (None, None, "idle", [], None))
        self.assertEqual(card["doing"], "Refactoring the parser")

    def test_an_agent_that_exited_is_not_running_and_keeps_its_last_activity(self):
        write_jsonl(self.claude_path(), claude_transcript(self.now))
        target = self.target("claude", CLAUDE_ID)
        self.card(target)
        os.unlink(self.claude_path())
        card = self.card(target, live=None)
        self.assertEqual(card["state"], "not_running")
        self.assertEqual(card["headline"], "Pulling Q3 exports", "the last title is kept")
        self.assertEqual(card["plan"]["current"], 2)
        self.assertIsNone(card["reader_error"], "a stopped agent is not read")
        shell = dict(self.live("claude"), agent=None)
        self.assertEqual(self.card(target, live=shell)["state"], "not_running")

    def test_states_and_the_live_lookup_through_the_api(self):
        api = FakeApi()
        api.set_response("agent.list", {"type": "agent_list", "agents": [self.live("claude", status="blocked")]})
        target = self.target("claude", CLAUDE_ID)
        self.assertEqual(A.card(self.layout, target, api=api, env=self.env)["state"], "blocked")
        api.set_response("agent.list", {"type": "agent_list", "agents": []})
        self.assertEqual(A.card(self.layout, target, api=api, env=self.env)["state"], "not_running")
        api.set_error("agent.list", "server_not_running", "down")
        self.assertEqual(A.card(self.layout, target, api=api, env=self.env)["state"], "unknown")
        self.assertEqual(A.card(self.layout, target, env=self.env)["state"], "unknown")
        self.assertEqual(self.card(target, live=self.live("claude", status="weird"))["state"], "unknown")

    def test_the_title_is_cleaned_and_redacted(self):
        live = self.live("claude", title="\x1b[1mdeploying\x1b[0m with {}".format(AWS_KEY))
        card = self.card({"terminal_id": "term_x", "pane_id": "w3:p2", "name": "x", "kind": "amp"}, live=live)
        self.assertEqual(card["headline"], "deploying with [redacted:aws_access_key]")

    def test_the_watched_flag_follows_watch_json(self):
        target = {"terminal_id": "term_x", "pane_id": "w3:p2", "name": "x", "kind": "amp"}
        self.assertFalse(self.card(target)["watched"])
        A.add_watch(self.ts.session, target, "human")
        self.assertTrue(self.card(target)["watched"])

    def test_cards_cover_watched_agents_and_the_teams_members_once(self):
        A.add_watch(self.ts.session, {"terminal_id": "term_x", "pane_id": "w3:p2", "name": "outsider", "kind": "amp"}, "human")
        A.add_watch(self.ts.session, {"terminal_id": "term_w1", "pane_id": "w2:p2", "name": "alpha-worker", "kind": "claude"}, "human")
        api = FakeApi()
        api.set_response("agent.list", {"type": "agent_list", "agents": [
            self.live("amp"), fake_agent("w2:p2", "term_w1", "claude", "alpha-worker", terminal_title_stripped="Working"),
            fake_agent("w2:p1", "term_r1", "codex", "alpha-reviewer")]})
        result = A.cards(self.layout, api, team="alpha", env=self.env)
        self.assertEqual([c["key"] for c in result], ["term_x", "term_w1", "term_r1"])
        worker = result[1]
        self.assertEqual((worker["team"], worker["role"], worker["watched"]), ("alpha", "worker", True))
        self.assertFalse(result[2]["watched"])
        self.assertEqual([c["key"] for c in A.cards(self.layout, api, env=self.env)], ["term_x", "term_w1"])
        self.assertEqual([c["key"] for c in A.cards(self.layout, api, team="alpha", env=self.env, include_watched=False)], ["term_r1", "term_w1"])
        self.assertEqual(len([c for m, c in api.calls if m == "agent.list"]), 3, "one agent.list per call, not per card")

    def test_plan_of_reads_the_callers_plan(self):
        write_jsonl(self.claude_path(), claude_transcript(self.now))
        member = dict(FAKE_MEMBERS[1], session=session("claude", CLAUDE_ID))
        plan = A.plan_of(self.layout, member, env=self.env)
        self.assertEqual((plan["current"], plan["source"]), (2, "todo"))
        self.assertIsNone(A.plan_of(self.layout, {"terminal_id": "term_q", "kind": "amp"}, env=self.env))


class DoingLineTests(unittest.TestCase):
    def test_plan_then_edit_then_command_then_headline(self):
        plan = A.make_plan([{"text": "a", "status": "completed"}, {"text": "run the tests", "status": "in_progress"}], "todo")
        actions = [{"icon": "run", "text": "pytest -q"}, {"icon": "edit", "text": "src/invoice.py"}, {"icon": "read", "text": "x"}]
        self.assertEqual(A.doing_line({"plan": plan, "actions": actions, "headline": "h"}), "▶ 2/2 run the tests")
        self.assertEqual(A.doing_line({"plan": dict(plan, current=None), "actions": actions, "headline": "h"}), "✎ invoice.py")
        self.assertEqual(A.doing_line({"actions": actions[:1], "headline": "h"}), "$ pytest", "the program, never its arguments")
        self.assertEqual(A.doing_line({"actions": [{"icon": "read", "text": "x"}], "headline": "Reviewing"}), "Reviewing")
        self.assertIsNone(A.doing_line({"actions": [], "headline": None}))
        self.assertIsNone(A.doing_line({}))

    def test_clipped_to_32_columns(self):
        line = A.doing_line({"headline": "漢字" * 40})
        self.assertLessEqual(A._sanitize.display_width(line), A.DOING_MAX_COLUMNS)
        line = A.doing_line({"actions": [{"icon": "run", "text": "python -m pytest tests/test_everything_in_the_repository.py"}]})
        self.assertLessEqual(A._sanitize.display_width(line), A.DOING_MAX_COLUMNS)
        self.assertTrue(line.startswith("$ python"))

    def test_token_commands_stamp_with_ttl_and_clear_when_stopped(self):
        commands = A.doing_token_commands([
            {"pane_id": "w1:p1", "state": "working", "doing": "✎ a.py"},
            {"pane_id": "w1:p2", "state": "not_running", "doing": "✎ b.py"},
            {"pane_id": "w1:p3", "state": "idle", "doing": None},
            {"pane_id": None, "state": "working", "doing": "x"},
        ])
        self.assertEqual([c.params() for c in commands], [
            {"pane_id": "w1:p1", "source": "herdr-synapse:watch", "tokens": {"team_doing": "✎ a.py"}, "ttl_ms": 60000},
            {"pane_id": "w1:p2", "source": "herdr-synapse:watch", "tokens": {"team_doing": None}},
            {"pane_id": "w1:p3", "source": "herdr-synapse:watch", "tokens": {"team_doing": None}},
        ])
        self.assertIsInstance(commands[0], roster.TokenCommand)


class WatchFileTests(unittest.TestCase):
    def setUp(self) -> None:
        self.ts = TempState()
        self.addCleanup(self.ts.cleanup)
        self.session = self.ts.session

    def test_add_remove_and_refresh(self):
        self.assertEqual(A.watched(self.session), [])
        entry = A.add_watch(self.session, {"terminal_id": "term_a", "pane_id": "w1:p1", "name": "a", "kind": "claude", "team": None}, "human")
        self.assertEqual((entry["by"], entry["terminal_id"]), ("human", "term_a"))
        self.assertTrue(entry["at"])
        doc = store.read_json(A.watch_path(self.session))
        self.assertEqual(doc["v"], 1)
        self.assertEqual(oct(os.stat(A.watch_path(self.session)).st_mode & 0o777), "0o600")
        again = A.add_watch(self.session, {"terminal_id": "term_a", "pane_id": "w9:p1", "team": "alpha"}, "someone-else")
        self.assertEqual((again["pane_id"], again["team"], again["name"], again["by"], again["at"]), ("w9:p1", "alpha", "a", "human", entry["at"]))
        self.assertTrue(A.is_watched(self.session, "term_a"))
        self.assertEqual(A.remove_watch(self.session, "term_a")["terminal_id"], "term_a")
        self.assertIsNone(A.remove_watch(self.session, "term_a"))
        self.assertFalse(A.is_watched(self.session, "term_a"))

    def test_the_limit(self):
        for i in range(A.MAX_WATCHED):
            A.add_watch(self.session, {"terminal_id": "term_{}".format(i)}, "human")
        with self.assertRaises(HerdrTeamError) as ctx:
            A.add_watch(self.session, {"terminal_id": "term_over"}, "human")
        self.assertEqual((ctx.exception.code, ctx.exception.details["max"]), ("watch_limit", 20))
        A.add_watch(self.session, {"terminal_id": "term_3", "pane_id": "w1:p3"}, "human")  # re-flagging is not an addition

    def test_bad_rows_and_ids_are_dropped(self):
        store.write_json(A.watch_path(self.session), {"v": 1, "agents": [
            {"terminal_id": "../escape"}, {"terminal_id": "term_ok", "name": 5}, "junk", {"terminal_id": "term_ok"}, {}]})
        self.assertEqual([e["terminal_id"] for e in A.watched(self.session)], ["term_ok"])
        with self.assertRaises(HerdrTeamError):
            A.add_watch(self.session, {"terminal_id": "bad/id"}, "human")
        store.write_json(A.watch_path(self.session), ["not", "a", "doc"])
        self.assertEqual(A.watched(self.session), [])

    def test_sync_follows_a_moved_pane_and_writes_only_on_change(self):
        A.add_watch(self.session, {"terminal_id": "term_a", "pane_id": "w1:p1", "name": "a", "kind": "claude"}, "human")
        self.assertFalse(A.sync_watch(self.session, {"term_a": {"pane_id": "w1:p1", "name": "a", "agent": "claude"}}))
        self.assertTrue(A.sync_watch(self.session, {"term_a": {"pane_id": "w4:p2", "name": "a2", "agent": "claude"}}))
        self.assertEqual((A.watched(self.session)[0]["pane_id"], A.watched(self.session)[0]["name"]), ("w4:p2", "a2"))

    def test_the_cache_goes_with_the_flag_and_old_ones_are_pruned(self):
        path = A.cache_path(self.session, "term_a")
        store.write_json(path, {"v": 1})
        A.add_watch(self.session, {"terminal_id": "term_a"}, "human")
        A.remove_watch(self.session, "term_a")
        self.assertFalse(path.exists())
        stale, kept, fresh = (A.cache_path(self.session, t) for t in ("term_old", "term_keep", "term_new"))
        for p in (stale, kept, fresh):
            store.write_json(p, {"v": 1})
        old = time.time() - 2 * A.CACHE_MAX_AGE_S
        os.utime(stale, (old, old))
        os.utime(kept, (old, old))
        self.assertEqual(A.prune_cache(self.session, {"term_keep"}), 1)
        self.assertEqual((stale.exists(), kept.exists(), fresh.exists()), (False, True, True))
        self.assertIsNone(A.cache_path(self.session, "../x"))

    def test_clear_doing_tokens_clears_stored_and_moved_panes(self):
        A.add_watch(self.session, {"terminal_id": "term_a", "pane_id": "w1:p1"}, "human")
        A.add_watch(self.session, {"terminal_id": "term_b", "pane_id": "w1:p2"}, "human")
        api = FakeApi()
        api.set_response("agent.list", {"type": "agent_list", "agents": [fake_agent("w5:p5", "term_a", "claude", None)]})
        self.assertEqual(A.clear_doing_tokens(self.ts.layout, api), 3)
        cleared = [p for m, p in api.calls if m == "pane.report_metadata"]
        self.assertEqual(sorted(p["pane_id"] for p in cleared), ["w1:p1", "w1:p2", "w5:p5"])
        self.assertTrue(all(p["tokens"] == {"team_doing": None} and p["source"] == "herdr-synapse:watch" for p in cleared))
        api.set_error("pane.report_metadata", "server_not_running", "down")
        self.assertEqual(A.clear_doing_tokens(self.ts.layout, api), 0)
        for entry in A.watched(self.session):
            A.remove_watch(self.session, entry["terminal_id"])
        self.assertEqual(A.clear_doing_tokens(self.ts.layout, FakeApi()), 0)


if __name__ == "__main__":
    unittest.main()
