"""Render the generated sections of ``docs/reference.md``.

The reference is deliberately a hybrid: prose and UI workflows stay easy to
edit by hand, while inventories that already have an executable source of
truth are replaced between named markers.  Run::

    python3 -m herdr_team.reference_docs --write

Use ``--check`` in tests or CI to fail when the checked-in reference is stale.
Python 3.9 and the standard library are the plugin's compatibility floor.
"""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
import re
import shlex
import sys
from typing import Any, Dict, Iterable, List, Sequence

from herdr_team import PLUGIN_ID
from herdr_team import cmd_misc, tui_model
from herdr_team.cli import COMMAND_MODULES, Command, build_parser, load_commands


PLUGIN_ROOT = Path(__file__).resolve().parent.parent
REFERENCE_PATH = PLUGIN_ROOT / "docs" / "reference.md"
MANIFEST_PATH = PLUGIN_ROOT / "herdr-plugin.toml"

SECTION_MARKERS = {
    "actions": ("<!-- BEGIN GENERATED: actions -->", "<!-- END GENERATED: actions -->"),
    "console": ("<!-- BEGIN GENERATED: console -->", "<!-- END GENERATED: console -->"),
    "cli": ("<!-- BEGIN GENERATED: cli -->", "<!-- END GENERATED: cli -->"),
}

MODULE_TITLES = {
    "herdr_team.cmd_roster": "Teams and members",
    "herdr_team.cmd_board": "Board, messages, and delivery",
    "herdr_team.cmd_misc": "Setup, controls, and maintenance",
    "herdr_team.cmd_update": "Plugin updates",
    "herdr_team.cmd_hooks": "Agent hooks",
    "herdr_team.cmd_skill": "Agent skill",
    "herdr_team.cmd_daemon": "Notifier service",
    "herdr_team.cmd_ui": "UI entrypoints",
    "herdr_team.cmd_usage": "Usage limits",
    "herdr_team.cmd_asks": "Human asks",
    "herdr_team.cmd_knowledge": "Shared knowledge",
    "herdr_team.cmd_models": "Models and effort",
    "herdr_team.cmd_links": "Team-to-team links",
}


def _markdown_cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def _command_usage(parser: argparse.ArgumentParser) -> str:
    """One deterministic line carrying argparse's complete invocation."""
    usage = " ".join(parser.format_usage().split())
    return usage[7:] if usage.startswith("usage: ") else usage


def _subparsers(parser: argparse.ArgumentParser) -> Dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    raise RuntimeError("herdr-synapse parser has no command registry")


def _global_option_name(action: argparse.Action) -> str:
    names = ", ".join(action.option_strings)
    if action.nargs == 0:
        return names
    if action.choices:
        value = "{" + ",".join(str(choice) for choice in action.choices) + "}"
    else:
        value = str(action.metavar or action.dest.upper())
    return "{} {}".format(names, value)


def _render_global_options(parser: argparse.ArgumentParser) -> List[str]:
    lines = [
        "### Global options",
        "",
        "These options are accepted before or after the command name.",
        "",
        "| Option | Meaning |",
        "| --- | --- |",
    ]
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            continue
        lines.append("| `{}` | {} |".format(
            _markdown_cell(_global_option_name(action)),
            _markdown_cell(action.help or ""),
        ))
    return lines


def _render_command(command: Command, parser: argparse.ArgumentParser) -> List[str]:
    summary = "<summary><code>{}</code> — {}</summary>".format(
        html.escape(command.name), html.escape(command.help)
    )
    return [
        "<details>",
        summary,
        "",
        "```text",
        _command_usage(parser),
        "```",
        "",
        "</details>",
        "",
    ]


def _commands_by_module(commands: Iterable[Command], hidden: bool) -> Dict[str, List[Command]]:
    grouped: Dict[str, List[Command]] = {module: [] for module in COMMAND_MODULES}
    for command in commands:
        if command.hidden == hidden:
            if command.module not in grouped:
                raise RuntimeError("no reference category for {}".format(command.module))
            grouped[command.module].append(command)
    return grouped


def render_cli_section() -> str:
    commands = load_commands()
    root = build_parser(commands)
    parsers = _subparsers(root)
    public = [command for command in commands if not command.hidden]
    internal = [command for command in commands if command.hidden]
    lines = [
        "<!-- Generated by `python3 -m herdr_team.reference_docs --write`; do not edit this block. -->",
        "",
        "This release exposes **{} public commands**. The **{} internal entrypoints** at the end are launched by Herdr or hooks and are not normal shell commands.".format(len(public), len(internal)),
        "",
    ]
    lines.extend(_render_global_options(root))
    lines.extend(["", "### Public commands", ""])
    grouped = _commands_by_module(commands, hidden=False)
    for module in COMMAND_MODULES:
        rows = grouped[module]
        if not rows:
            continue
        lines.extend(["#### {}".format(MODULE_TITLES[module]), ""])
        for command in rows:
            lines.extend(_render_command(command, parsers[command.name]))
    lines.extend([
        "### Internal plugin entrypoints",
        "",
        "These exist in the parser so Herdr panes and hooks can call the same package. Use the public `ui`, `hooks`, and other commands instead.",
        "",
    ])
    for command in internal:
        lines.extend(_render_command(command, parsers[command.name]))
    return "\n".join(lines).rstrip()


_BLOCK_RE = re.compile(r"(?ms)^\[\[actions\]\]\s*\n(.*?)(?=^\[\[|\Z)")
_VALUE_RE = re.compile(r"(?m)^([a-z_]+)\s*=\s*(.+)$")


def manifest_actions(text: str) -> List[Dict[str, Any]]:
    """Read the small JSON-compatible values used by each manifest action."""
    actions: List[Dict[str, Any]] = []
    for match in _BLOCK_RE.finditer(text):
        values: Dict[str, Any] = {}
        for item in _VALUE_RE.finditer(match.group(1)):
            try:
                values[item.group(1)] = json.loads(item.group(2))
            except ValueError as err:
                raise RuntimeError("cannot parse action {}: {}".format(item.group(1), err))
        if "id" not in values or "title" not in values:
            raise RuntimeError("manifest action lacks id or title")
        actions.append(values)
    return actions


def _shell_join(parts: Sequence[Any]) -> str:
    return " ".join(shlex.quote(str(part)) for part in parts)


def render_actions_section() -> str:
    actions = manifest_actions(MANIFEST_PATH.read_text(encoding="utf-8"))
    action_ids = {str(action["id"]) for action in actions}
    missing = [action for action in cmd_misc.KEY_ACTIONS if action not in action_ids]
    if missing:
        raise RuntimeError("default keys name missing plugin actions: {}".format(", ".join(missing)))
    lines = [
        "<!-- Generated by `python3 -m herdr_team.reference_docs --write`; do not edit this block. -->",
        "",
        "#### Default global shortcuts",
        "",
        "Synapse does not install bindings automatically. `herdr-synapse keys print` emits these entries and `herdr-synapse keys check` reports collisions.",
        "",
        "| Shortcut | Action | What it opens or changes |",
        "| --- | --- | --- |",
    ]
    for action in cmd_misc.KEY_ACTIONS:
        lines.append("| `{}` | `{}` | {} |".format(
            _markdown_cell(cmd_misc.KEYS[action]),
            _markdown_cell("{}.{}".format(PLUGIN_ID, action)),
            _markdown_cell(cmd_misc.KEY_DESCRIPTIONS[action]),
        ))
    lines.extend([
        "",
        "#### Every plugin action",
        "",
        "Actions can also be launched without a binding through `herdr plugin action invoke`.",
        "",
        "| Action | Context | Invocation | Underlying command |",
        "| --- | --- | --- | --- |",
    ])
    for action in actions:
        action_id = str(action["id"])
        contexts = ", ".join(str(value) for value in action.get("contexts") or [])
        command = _shell_join(action.get("command") or [])
        lines.append("| {} | {} | `{}` | `{}` |".format(
            _markdown_cell(action.get("title") or action_id),
            _markdown_cell(contexts),
            _markdown_cell("herdr plugin action invoke {}.{}".format(PLUGIN_ID, action_id)),
            _markdown_cell(command),
        ))
    return "\n".join(lines)


def render_console_section() -> str:
    missing = [command for command in tui_model.SLASH_COMMANDS if command not in tui_model.SLASH_USAGE]
    extra = [command for command in tui_model.SLASH_USAGE if command not in tui_model.SLASH_COMMANDS]
    if missing or extra:
        raise RuntimeError("console command registry mismatch: missing={!r}, extra={!r}".format(missing, extra))
    lines = [
        "<!-- Generated by `python3 -m herdr_team.reference_docs --write`; do not edit this block. -->",
        "",
        "| Command | Parameters | What it does |",
        "| --- | --- | --- |",
    ]
    for command in tui_model.SLASH_COMMANDS:
        placeholder, purpose = tui_model.SLASH_USAGE[command]
        lines.append("| `{}` | `{}` | {} |".format(
            _markdown_cell(command),
            _markdown_cell(placeholder or "—"),
            _markdown_cell(purpose),
        ))
    return "\n".join(lines)


def _replace_section(document: str, section: str, body: str) -> str:
    begin, end = SECTION_MARKERS[section]
    if document.count(begin) != 1 or document.count(end) != 1:
        raise RuntimeError("docs/reference.md must contain exactly one {} marker pair".format(section))
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    return pattern.sub(begin + "\n" + body.rstrip() + "\n" + end, document, count=1)


def render_document(document: str) -> str:
    rendered = document
    rendered = _replace_section(rendered, "actions", render_actions_section())
    rendered = _replace_section(rendered, "console", render_console_section())
    rendered = _replace_section(rendered, "cli", render_cli_section())
    return rendered.rstrip() + "\n"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="render docs/reference.md from the Synapse registries")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="replace generated sections in docs/reference.md")
    mode.add_argument("--check", action="store_true", help="fail when docs/reference.md is stale")
    return parser


def main(argv: Sequence[str] = ()) -> int:
    args = _parser().parse_args(list(argv))
    current = REFERENCE_PATH.read_text(encoding="utf-8")
    rendered = render_document(current)
    if args.check:
        if rendered != current:
            sys.stderr.write("docs/reference.md is stale; run python3 -m herdr_team.reference_docs --write\n")
            return 1
        return 0
    if args.write:
        REFERENCE_PATH.write_text(rendered, encoding="utf-8")
        return 0
    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
